# -*- coding: utf-8 -*-
import json
from pathlib import Path

def q(n, stem, options, answer, trap, why, fix, topic, directions="", table=None, figs=None, caption=""):
    return {
        "n": n,
        "stem": stem,
        "options": options,
        "answer": answer,
        "trap": trap,
        "why": why,
        "fix": fix,
        "topic": topic,
        "figs": figs or [],
        "caption": caption,
        "directions": directions,
        "table": table,
    }

p1 = [
    q(1,
      "Respiration is best defined as",
      {"A": "gas exchange between the lungs and the air.",
       "B": "the intake of oxygen only.",
       "C": "the release of energy from organic compounds in living cells.",
       "D": "the production of oxygen inside mitochondria."},
      "C", "A",
      "Gas exchange supplies oxygen and removes carbon dioxide. It is not the chemical process that releases energy.",
      "Respiration is the release of energy from organic food in living cells.",
      "Meaning of respiration"),
    q(2,
      "Which statement about where respiration occurs is correct?",
      {"A": "Only animals respire.",
       "B": "Only organisms without chloroplasts respire.",
       "C": "All living organisms respire.",
       "D": "Green plants respire only at night."},
      "C", "D",
      "Plants respire in the light as well as in the dark. Photosynthesis does not replace respiration.",
      "Every living cell respires.",
      "Meaning of respiration"),
    q(3,
      "Which description of a green plant is correct?",
      {"A": "It photosynthesises in the day and respires only at night.",
       "B": "It respires all the time. It also photosynthesises in the light.",
       "C": "It does not respire, because it makes its own food.",
       "D": "It stops respiration when stomata close."},
      "B", "A",
      "The usual slip is that respiration is switched off in daylight. Energy is still needed in the light.",
      "Respiration is continuous. Photosynthesis is added in the light.",
      "Plants day and night"),
    q(4,
      "Which comparison of burning and respiration is correct?",
      {"A": "Both always need oxygen. Only burning needs enzymes.",
       "B": "Burning can be a single-step oxidation. Respiration is a series of enzyme-controlled reactions.",
       "C": "Both store most of the released energy as ATP.",
       "D": "Respiration releases energy from inorganic substances only."},
      "B", "A",
      "Anaerobic respiration does not use oxygen. Enzymes belong to respiration, not to a fire.",
      "Respiration is enzyme-controlled and stepwise. Burning is not.",
      "Burning vs respiration"),
    q(5,
      "The useful product of respiration for the cell is mainly",
      {"A": "heat.",
       "B": "ATP.",
       "C": "carbon dioxide.",
       "D": "water."},
      "B", "A",
      "Heat is a by-product. The cell uses ATP to drive metabolism.",
      "ATP is the useful energy currency.",
      "ATP"),
    q(6,
      "Which word equation for aerobic respiration of glucose is correct?",
      {"A": "glucose + oxygen → carbon dioxide + water + energy",
       "B": "glucose → ethanol + carbon dioxide + energy",
       "C": "carbon dioxide + water → glucose + oxygen",
       "D": "glucose + water → carbon dioxide + oxygen + energy"},
      "A", "B",
      "B is yeast anaerobic respiration. C is photosynthesis.",
      "Aerobic respiration uses oxygen and produces carbon dioxide and water.",
      "Aerobic respiration"),
    q(7,
      "Anaerobic respiration in yeast produces",
      {"A": "lactate only.",
       "B": "ethanol and carbon dioxide.",
       "C": "oxygen and water.",
       "D": "ATP with no organic waste."},
      "B", "A",
      "Lactate is the animal-muscle product. Yeast fermentation gives ethanol and carbon dioxide.",
      "Yeast: glucose → ethanol + carbon dioxide + energy.",
      "Anaerobic respiration"),
    q(8,
      "During a short sprint, human muscle may produce",
      {"A": "ethanol.",
       "B": "lactate (lactic acid).",
       "C": "oxygen.",
       "D": "starch."},
      "B", "A",
      "Human muscle does not make ethanol. That is yeast.",
      "Anaerobic muscle respiration produces lactate.",
      "Anaerobic respiration"),
    q(9,
      "Oxygen debt after vigorous exercise is paid by",
      {"A": "stopping all respiration.",
       "B": "using extra oxygen to oxidise or convert lactate and to restore ATP and phosphocreatine.",
       "C": "continuing anaerobic respiration in the lungs.",
       "D": "holding the breath."},
      "B", "C",
      "The debt is not paid in the lungs by more fermentation. Extra oxygen is used after the exercise.",
      "Extra oxygen is used to deal with lactate and to restore energy stores.",
      "Oxygen debt"),
    q(10,
      "Germinating seeds are placed in a vacuum flask with a thermometer. The temperature inside the flask rises. The best explanation is",
      {"A": "photosynthesis in the seeds.",
       "B": "respiration, which releases heat as a by-product.",
       "C": "evaporation of water from the seeds.",
       "D": "heat produced by the thermometer."},
      "B", "A",
      "Seeds in a closed flask are not photosynthesising as a green leaf in light would. Heat is from respiration.",
      "Respiration of the germinating seeds releases heat.",
      "Seed experiment",
      figs=["media/seeds_flask.svg"],
      caption="Vacuum flask with germinating seeds and a thermometer."),
    q(11,
      "The same flask is set up with boiled seeds. The temperature barely rises because",
      {"A": "boiling adds extra oxygen.",
       "B": "enzymes are denatured, so respiration stops.",
       "C": "boiled seeds photosynthesise faster.",
       "D": "boiling removes all water, so there is no heat to measure."},
      "B", "D",
      "The control is about killing enzymes, not about drying the seeds completely.",
      "Boiling denatures respiratory enzymes.",
      "Seed experiment"),
    q(12,
      "Germinating seeds are enclosed with potassium hydroxide (KOH). A manometer is attached. The liquid moves towards the seeds. Why?",
      {"A": "The seeds produce oxygen.",
       "B": "KOH absorbs carbon dioxide, and oxygen is used in respiration, so the gas volume falls.",
       "C": "Water vapour from the seeds increases the pressure.",
       "D": "Heat from respiration expands the air and always pulls liquid towards the seeds."},
      "B", "D",
      "Heat expansion would push the liquid the other way. The fall in volume is oxygen used after CO2 is absorbed.",
      "Oxygen is used. Carbon dioxide is absorbed by KOH, so the volume of gas falls.",
      "Respirometer",
      figs=["media/respirometer.svg"],
      caption="Closed tube with germinating seeds and KOH, connected to a manometer."),
    q(13,
      "Gas from a yeast-and-glucose mixture is bubbled through lime water, which turns milky. This shows that",
      {"A": "oxygen is produced.",
       "B": "carbon dioxide is produced.",
       "C": "ethanol is produced.",
       "D": "nitrogen is used."},
      "B", "A",
      "Milky lime water is the test for carbon dioxide, not oxygen.",
      "Lime water tests for carbon dioxide.",
      "Yeast experiment",
      figs=["media/yeast_setup.svg"],
      caption="Yeast in glucose solution, with a delivery tube to lime water."),
    q(14,
      "Hydrogencarbonate indicator is used with small animals in the dark (no plants). The indicator is expected to go",
      {"A": "purple, because carbon dioxide is removed.",
       "B": "yellow, because carbon dioxide is added.",
       "C": "blue, because oxygen is used.",
       "D": "colourless, because ethanol is formed."},
      "B", "A",
      "Purple is the colour for less carbon dioxide (as in photosynthesis in light). Animals add carbon dioxide.",
      "More carbon dioxide turns the indicator yellow.",
      "Gas tests"),
    q(15,
      "Which statements are correct?\n(1) Respiration can occur in the cytoplasm and in mitochondria.\n(2) Aerobic respiration needs oxygen.\n(3) Anaerobic respiration in muscle needs oxygen.",
      {"A": "(1) and (2) only",
       "B": "(1) and (3) only",
       "C": "(2) and (3) only",
       "D": "(1), (2) and (3)"},
      "A", "D",
      "Anaerobic muscle respiration does not use oxygen. Glycolysis is in the cytoplasm; later aerobic steps are in mitochondria.",
      "(1) and (2) only.",
      "Aerobic vs anaerobic"),
    q(16,
      "The purpose of respiration is",
      {"A": "to take in oxygen.",
       "B": "to provide energy for metabolic activities.",
       "C": "to produce carbon dioxide so that plants can photosynthesise.",
       "D": "to cool the body."},
      "B", "A",
      "Taking in oxygen is a means, not the purpose. Cells respire in order to obtain usable energy.",
      "Respiration supplies energy for metabolism.",
      "Meaning of respiration"),
]

p2 = [
    q(17,
      "Glycolysis takes place in the",
      {"A": "mitochondrial matrix.",
       "B": "cytosol (cytoplasm).",
       "C": "cristae.",
       "D": "nucleus."},
      "B", "A",
      "The matrix is for the Krebs cycle. Glycolysis is outside the mitochondrion.",
      "Glycolysis is in the cytoplasm.",
      "Sites"),
    q(18,
      "The Krebs cycle takes place in the",
      {"A": "cytoplasm.",
       "B": "mitochondrial matrix.",
       "C": "nucleus.",
       "D": "chloroplast stroma."},
      "B", "A",
      "After pyruvate enters the mitochondrion, the cycle runs in the matrix, not in the cytosol.",
      "Krebs cycle: mitochondrial matrix.",
      "Sites"),
    q(19,
      "The electron transport chain of aerobic respiration is located on the",
      {"A": "nuclear envelope.",
       "B": "cristae (inner mitochondrial membrane).",
       "C": "cell wall.",
       "D": "tonoplast of the vacuole."},
      "B", "A",
      "The folded inner membrane holds the carriers that make most of the ATP.",
      "Electron transport is on the cristae.",
      "Sites",
      figs=["media/mitochondrion.svg"],
      caption="Mitochondrion. X cytoplasm; Y matrix; Z inner membrane / crista."),
    q(20,
      "On the diagram, where is most of the ATP from aerobic respiration made?",
      {"A": "X",
       "B": "Y",
       "C": "Z",
       "D": "The cell wall (not labelled)."},
      "C", "A",
      "X is cytoplasm (glycolysis gives only a little ATP). Most ATP is from the electron transport chain on Z.",
      "Most ATP is made at the inner membrane (Z).",
      "Sites",
      figs=["media/mitochondrion.svg"],
      caption="Mitochondrion. X cytoplasm; Y matrix; Z inner membrane / crista."),
    q(21,
      "Compared with anaerobic respiration of one glucose molecule, aerobic respiration",
      {"A": "produces much less ATP.",
       "B": "produces much more ATP.",
       "C": "produces ethanol in human muscle.",
       "D": "does not need enzymes."},
      "B", "A",
      "The trap is reversing the yield. Complete oxidation gives far more ATP than fermentation.",
      "Aerobic respiration yields much more ATP per glucose.",
      "ATP yield"),
    q(22,
      "In respiration, NAD / NADH mainly",
      {"A": "carries oxygen to the lungs.",
       "B": "carries hydrogen / electrons to the electron transport chain.",
       "C": "is a waste product exhaled as gas.",
       "D": "stores glucose as starch."},
      "B", "A",
      "NAD is a coenzyme for hydrogen, not a blood pigment for oxygen.",
      "Reduced NAD delivers hydrogen to the cristae.",
      "Electron transport"),
    q(23,
      "Cyanide blocks the electron transport chain. Aerobic ATP production then",
      {"A": "increases.",
       "B": "falls sharply.",
       "C": "is unaffected, because glycolysis still uses oxygen.",
       "D": "switches to photosynthesis in animal cells."},
      "B", "C",
      "Glycolysis does not use oxygen. Blocking the chain stops oxidative phosphorylation.",
      "Most aerobic ATP is lost if the electron transport chain is blocked.",
      "Electron transport"),
    q(24,
      "Respiratory quotient (RQ) is",
      {"A": "volume of oxygen used / volume of carbon dioxide produced.",
       "B": "volume of carbon dioxide produced / volume of oxygen used.",
       "C": "ATP produced / glucose used.",
       "D": "water produced / oxygen used."},
      "B", "A",
      "The two gas volumes are often swapped.",
      "RQ = CO₂ given out / O₂ taken in.",
      "RQ"),
    q(25,
      "For complete aerobic respiration of carbohydrate, RQ is about",
      {"A": "0.7",
       "B": "1.0",
       "C": "0.5",
       "D": "4.0"},
      "B", "A",
      "0.7 is typical of lipid. Carbohydrate gives equal volumes of CO₂ and O₂, so RQ ≈ 1.",
      "Carbohydrate RQ is about 1.0.",
      "RQ"),
    q(26,
      "For complete aerobic respiration of lipid, RQ is typically",
      {"A": "about 1.0",
       "B": "about 0.7",
       "C": "about 2.0",
       "D": "zero"},
      "B", "A",
      "Lipid uses more oxygen relative to the carbon dioxide produced, so RQ is below 1.",
      "Lipid RQ is about 0.7.",
      "RQ"),
    q(27,
      "In bright light a green leaf may show a net uptake of carbon dioxide because",
      {"A": "respiration has stopped.",
       "B": "the rate of photosynthesis exceeds the rate of respiration.",
       "C": "stomata are closed.",
       "D": "mitochondria have been converted into chloroplasts."},
      "B", "A",
      "Respiration continues. Net gas exchange depends on which process is faster.",
      "Photosynthesis is faster than respiration, so there is net CO₂ uptake.",
      "Plants day and night"),
    q(28,
      "At night a green plant typically",
      {"A": "has a net release of carbon dioxide from respiration.",
       "B": "produces a net surplus of oxygen.",
       "C": "does not respire.",
       "D": "has an RQ of zero because there is no gas exchange."},
      "A", "C",
      "Photosynthesis stops without light. Respiration continues, so CO₂ is given out.",
      "Night: respiration only, so net carbon dioxide release.",
      "Plants day and night"),
    q(29,
      "The compensation point is the light intensity at which",
      {"A": "all stomata close.",
       "B": "the rate of photosynthesis equals the rate of respiration, so net carbon dioxide exchange is zero.",
       "C": "the plant dies.",
       "D": "only anaerobic respiration occurs."},
      "B", "A",
      "It is a gas-exchange balance, not a stomatal reflex.",
      "Photosynthesis rate = respiration rate.",
      "Plants day and night"),
    q(30,
      "In a respirometer with KOH present, the fall in gas volume measures",
      {"A": "carbon dioxide produced.",
       "B": "oxygen consumed.",
       "C": "nitrogen used.",
       "D": "water evaporated."},
      "B", "A",
      "KOH removes the carbon dioxide. The remaining volume change is oxygen used.",
      "With KOH, the manometer records oxygen uptake.",
      "Respirometer"),
    q(31,
      "If KOH is omitted and the tissue has RQ = 1, the manometer",
      {"A": "still falls at the same rate as with KOH.",
       "B": "shows little net change, because carbon dioxide produced equals oxygen used.",
       "C": "rises, because oxygen is produced.",
       "D": "always falls twice as fast."},
      "B", "A",
      "Without an absorber, equal volumes of O₂ in and CO₂ out cancel. RQ = 1 is carbohydrate.",
      "Equal CO₂ and O₂ give no net volume change.",
      "Respirometer"),
    q(32,
      "Which statements are correct?\n(1) Heat is a by-product of respiration.\n(2) Respiratory enzymes can be denatured by high temperature.\n(3) Respiration occurs only in animals.",
      {"A": "(1) and (2) only",
       "B": "(1) and (3) only",
       "C": "(2) and (3) only",
       "D": "(1), (2) and (3)"},
      "A", "D",
      "Plants, fungi and bacteria also respire. Heat and enzyme sensitivity are both true.",
      "(1) and (2) only.",
      "Meaning of respiration"),
]

bank = [
    {"id": "1", "title": "Practice 1", "subtitle": "Meaning, gases and experiments", "items": p1},
    {"id": "2", "title": "Practice 2", "subtitle": "Mitochondria, RQ and plants", "items": p2},
]

out = Path(__file__).with_name("questions.js")
out.write_text("window.RESPIRATION_BANK = " + json.dumps(bank, ensure_ascii=False) + ";\n", encoding="utf-8")
print("wrote", out, "items", len(p1), len(p2))
