# -*- coding: utf-8 -*-
import json
from pathlib import Path

def q(n, stem, options, answer, trap, why, fix, topic, directions="", table=None, figs=None, caption=""):
    return {
        "n": n,
        "stem": stem,
        "options": options,
        "answer": answer,
        "trap": trap,
        "why": why,
        "fix": fix,
        "topic": topic,
        "figs": figs or [],
        "caption": caption,
        "directions": directions,
        "table": table,
    }

p1 = [
    q(1,
      "Which description of diffusion is correct?",
      {"A": "Net movement of particles from a region of lower concentration to a region of higher concentration, using ATP.",
       "B": "Net movement of particles from a region of higher concentration to a region of lower concentration, without using ATP.",
       "C": "Net movement of water only, through a differentially permeable membrane.",
       "D": "Uptake of ions against a concentration gradient, using ATP."},
      "B", "C",
      "Osmosis is a special case of diffusion of water. Diffusion itself is not limited to water, and it does not use ATP.",
      "Diffusion is net movement down a concentration gradient and does not use ATP.",
      "Diffusion"),
    q(2,
      "Which substance can cross a living cell membrane most readily by simple diffusion?",
      {"A": "Oxygen", "B": "Starch", "C": "A protein molecule", "D": "DNA"},
      "A", "B",
      "Starch is a large polymer. It does not cross a living membrane by simple diffusion.",
      "Small, non-polar molecules such as oxygen cross the membrane readily by simple diffusion.",
      "Diffusion"),
    q(3,
      "Osmosis is the",
      {"A": "net movement of solute from a concentrated solution to a dilute solution through a fully permeable wall.",
       "B": "active pumping of water into a cell using ATP.",
       "C": "movement of any dissolved substance through a cell wall.",
       "D": "net movement of water molecules from a region of higher water potential to a region of lower water potential through a differentially permeable membrane."},
      "D", "A",
      "Osmosis is about water, not solute, and it needs a differentially permeable membrane. A cell wall is fully permeable.",
      "Water moves from higher water potential to lower water potential through a differentially permeable membrane.",
      "Osmosis"),
    q(4,
      "Which solution has the highest water potential?",
      {"A": "0.5 mol dm⁻³ sucrose solution",
       "B": "0.2 mol dm⁻³ sucrose solution",
       "C": "Distilled water",
       "D": "1.0 mol dm⁻³ sucrose solution"},
      "C", "B",
      "Dissolved sucrose lowers water potential. Distilled water has no solute, so its water potential is the highest (0 kPa).",
      "Distilled water has the highest water potential.",
      "Water potential"),
    q(5,
      "Two solutions are separated by a differentially permeable membrane. Solution X is 0.1 mol dm⁻³ glucose. Solution Y is 0.4 mol dm⁻³ glucose. Which statement is correct?",
      {"A": "Water potential is higher in Y than in X, so water moves from Y to X.",
       "B": "Glucose moves from X to Y by osmosis.",
       "C": "Water potential is higher in X than in Y, so water moves from X to Y.",
       "D": "There is no net movement of water because both sides contain glucose."},
      "C", "A",
      "The more concentrated solution has the lower water potential. Water therefore leaves X and enters Y.",
      "Water moves from the dilute side (X) to the concentrated side (Y).",
      "Water potential"),
    q(6,
      "A red blood cell is placed in distilled water. What happens, and why?",
      {"A": "It becomes turgid and does not burst, because the cell wall resists the pressure.",
       "B": "It bursts, because water enters by osmosis and there is no cell wall to stop expansion.",
       "C": "It shrinks, because water leaves the cell.",
       "D": "Nothing changes, because the membrane is impermeable to water."},
      "B", "A",
      "A red blood cell has no cell wall. Turgidity without bursting is a plant-cell result.",
      "Water enters by osmosis and the cell haemolyses.",
      "Animal cells"),
    q(7,
      "A red blood cell is placed in a concentrated sodium chloride solution. The cell",
      {"A": "bursts, because salt rushes in.",
       "B": "becomes turgid, because the cytoplasm gains water.",
       "C": "is plasmolysed, because the cytoplasm pulls away from a cell wall.",
       "D": "becomes crenated, because water leaves by osmosis."},
      "D", "C",
      "Plasmolysis needs a cell wall. An animal cell has none, so the correct word is crenation.",
      "Water leaves and the cell shrinks (crenation).",
      "Animal cells"),
    q(8,
      "An onion epidermal cell is placed in distilled water. Which result is correct?",
      {"A": "The cell bursts, as in a red blood cell.",
       "B": "The cytoplasm pulls away from the cell wall.",
       "C": "The cell becomes turgid. It does not burst, because the cell wall limits expansion.",
       "D": "The cell wall stops all water from entering."},
      "C", "A",
      "Plant cells do not haemolyse in distilled water. The fully permeable wall lets water in, then resists further swelling.",
      "The cell becomes turgid and is supported by the wall.",
      "Plant cells"),
    q(9,
      "The diagrams show two plant cells, P and Q, after 20 minutes in different solutions. Which matching is correct?",
      {"A": "P is turgid in distilled water. Q is plasmolysed in concentrated sucrose solution.",
       "B": "P is plasmolysed in distilled water. Q is turgid in concentrated sucrose solution.",
       "C": "P and Q are both turgid, because the cell wall is differentially permeable.",
       "D": "P has burst. Q has a fully permeable membrane."},
      "A", "B",
      "The cytoplasm filling the wall is turgid. The shrunken cytoplasm inside the wall is plasmolysis, which happens in a concentrated solution.",
      "P is turgid. Q is plasmolysed.",
      "Plant cells",
      figs=["media/plasmolysis.svg"],
      caption="Cell P (left) and cell Q (right). The outer box is the cell wall."),
    q(10,
      "Which comparison of the cell wall and the cell membrane is correct?",
      {"A": "The wall is differentially permeable. The membrane is fully permeable.",
       "B": "Both are fully permeable.",
       "C": "Both stop water but allow sucrose to pass.",
       "D": "The wall is fully permeable. The membrane is differentially permeable."},
      "D", "A",
      "The two jobs are often swapped. Control of which dissolved substances enter is the job of the membrane, not the wall.",
      "The wall is fully permeable. The membrane is differentially permeable.",
      "Membrane vs wall"),
    q(11,
      "Which statements about a living cell membrane are correct?\n(1) Water can cross it by osmosis.\n(2) Starch can cross it by simple diffusion.\n(3) It can control the entry of some solutes.",
      {"A": "(1) and (2) only", "B": "(1) and (3) only", "C": "(2) and (3) only", "D": "(1), (2) and (3)"},
      "B", "D",
      "Starch is too large to cross by simple diffusion. Water can, and the membrane does control some solutes.",
      "(1) and (3) only.",
      "Membrane vs wall"),
    q(12,
      "Incipient plasmolysis is the point at which",
      {"A": "the cell has burst.",
       "B": "the cytoplasm has just started to pull away from the cell wall in some cells.",
       "C": "the cell wall has dissolved.",
       "D": "the vacuole has filled with sucrose from outside the cell."},
      "B", "D",
      "Sucrose does not flood into the vacuole through a living membrane at this point. The cytoplasm is just losing contact with the wall.",
      "The cytoplasm has just begun to pull away from the wall.",
      "Plant cells"),
    q(13,
      "Distilled water is added to a red blood cell and to an onion epidermal cell. Why does only the red blood cell burst?",
      {"A": "The onion cell membrane is impermeable to water.",
       "B": "The onion cell has a cell wall that resists the turgor pressure.",
       "C": "The red blood cell has a lower water potential than distilled water, but the onion cell does not.",
       "D": "Only animal cells carry out osmosis."},
      "B", "C",
      "Water enters both cells. The difference is the wall, not a difference in whether osmosis occurs.",
      "The plant cell wall stops the cell from bursting.",
      "Plant cells"),
    q(14,
      "A plant cell has a water potential of −400 kPa. It is placed in a solution of water potential −700 kPa. What happens?",
      {"A": "Net water gain by the cell.",
       "B": "No net movement of water.",
       "C": "Net water loss from the cell.",
       "D": "Sucrose is pumped into the cell to equalise the water potentials."},
      "C", "A",
      "Water moves to the more negative water potential, so it leaves the cell.",
      "The external solution has the lower water potential, so the cell loses water.",
      "Water potential"),
    q(15,
      "Four cubes of agar containing indicator are placed in acid. Which cube changes colour throughout first, and why?",
      {"A": "The smallest cube, because it has the largest surface area to volume ratio.",
       "B": "The largest cube, because it has the largest surface area.",
       "C": "The smallest cube, because it has the smallest surface area to volume ratio.",
       "D": "All cubes take the same time, because diffusion does not depend on size."},
      "A", "B",
      "A large cube has more surface, but a smaller surface area to volume ratio, so the centre is reached more slowly.",
      "The smallest cube has the largest SA:V, so diffusion to the centre is fastest.",
      "SA:V"),
    q(16,
      "Which features of a root hair cell increase the rate at which water is absorbed?\n(1) A long projection, giving a large surface area\n(2) A thin cell wall\n(3) Chloroplasts for photosynthesis",
      {"A": "(1) and (2) only", "B": "(1) and (3) only", "C": "(2) and (3) only", "D": "(1), (2) and (3)"},
      "A", "D",
      "Root hair cells have no chloroplasts. Surface area and a thin wall do speed water uptake.",
      "(1) and (2) only.",
      "SA:V"),
]

p2 = [
    q(17,
      "A Visking tubing bag containing starch solution is placed in iodine solution. After 20 minutes the liquid inside the bag is blue-black. The liquid outside stays brown. Which conclusion is correct?",
      {"A": "Iodine molecules entered the bag. Starch did not leave the bag.",
       "B": "Starch left the bag. Iodine did not enter.",
       "C": "Both starch and iodine crossed the tubing freely.",
       "D": "The tubing is impermeable to iodine."},
      "A", "B",
      "Blue-black inside means iodine met starch inside. Brown outside means starch did not escape.",
      "Iodine entered. Starch stayed inside.",
      "Visking tubing",
      figs=["media/visking.svg"],
      caption="Visking tubing containing starch solution, placed in iodine solution."),
    q(18,
      "A Visking tubing bag containing a mixture of starch and glucose is placed in distilled water. After 30 minutes the water outside is tested. Which result is expected?",
      {"A": "Benedict's test positive. Iodine test negative.",
       "B": "Benedict's test negative. Iodine test positive.",
       "C": "Both tests positive.",
       "D": "Both tests negative."},
      "A", "C",
      "Glucose is small enough to leave. Starch is not, so iodine outside stays brown.",
      "Glucose is found outside. Starch is not.",
      "Visking tubing"),
    q(19,
      "Visking tubing is used as a model of a cell membrane because it is",
      {"A": "alive and able to respire.",
       "B": "fully permeable to starch and protein.",
       "C": "able to carry out active transport.",
       "D": "differentially permeable."},
      "D", "C",
      "The tubing does not use ATP. It only lets some molecules through and holds others back.",
      "It is differentially permeable.",
      "Visking tubing"),
    q(20,
      "Equal-sized potato cylinders are blotted, weighed, and left in sucrose solutions. After 1 hour they are blotted and weighed again. A cylinder in 0.8 mol dm⁻³ sucrose has a lower mass. The best explanation is",
      {"A": "sucrose entered the cells by osmosis.",
       "B": "the cells burst and lost cytoplasm.",
       "C": "water left the cells by osmosis.",
       "D": "starch was converted to sucrose and leaked out."},
      "C", "A",
      "Osmosis is the movement of water, not sucrose. The concentrated solution has the lower water potential, so water leaves.",
      "Water left the cells by osmosis.",
      "Potato experiment"),
    q(21,
      "The table shows the percentage change in mass of potato cylinders after 1 hour.",
      {"A": "0.1 mol dm⁻³", "B": "0.3 mol dm⁻³", "C": "0.4 mol dm⁻³", "D": "0.6 mol dm⁻³"},
      "B", "C",
      "The isotonic point is where mass change is zero, between a small gain and a small loss — here 0.3 mol dm⁻³.",
      "0.3 mol dm⁻³, where the mass change is about zero.",
      "Potato experiment",
      directions="Directions: Which sucrose concentration is closest to the water potential of the potato cells?",
      table=[
          ["Sucrose concentration / mol dm⁻³", "Change in mass / %"],
          ["0.0", "+12"],
          ["0.1", "+7"],
          ["0.3", "0"],
          ["0.4", "−5"],
          ["0.6", "−11"],
      ]),
    q(22,
      "In the potato-cylinder experiment, why are the cylinders blotted before each weighing?",
      {"A": "To kill the cells so osmosis stops.",
       "B": "To remove surface liquid so the mass change is due to water movement in or out of cells.",
       "C": "To add extra sucrose to the surface.",
       "D": "To make the cylinders longer."},
      "B", "A",
      "Blotting is not a way of killing cells. It removes liquid that is not inside the tissue.",
      "Surface liquid would hide the real mass change of the cells.",
      "Potato experiment"),
    q(23,
      "Beetroot discs are rinsed, then placed in water at different temperatures. Red pigment appears in the water at 70 °C but not at 20 °C. The best explanation is that at 70 °C",
      {"A": "the pigment molecules become small enough to diffuse at any temperature.",
       "B": "photosynthesis produces extra pigment.",
       "C": "the cell wall becomes differentially permeable.",
       "D": "the cell membrane is damaged, so pigment can leak out."},
      "D", "C",
      "The wall is already fully permeable. Leakage of a large pigment means the membrane has lost its control.",
      "High temperature damages the membrane, so pigment leaks.",
      "Beetroot / temperature"),
    q(24,
      "Which treatment increases the permeability of a living cell membrane?\n(1) High temperature that denatures membrane proteins\n(2) Ethanol, which dissolves membrane lipids\n(3) Placing the cell in an isotonic solution at room temperature",
      {"A": "(1) and (2) only", "B": "(1) and (3) only", "C": "(2) and (3) only", "D": "(1), (2) and (3)"},
      "A", "D",
      "An isotonic solution at room temperature does not damage the membrane. Heat and ethanol do.",
      "(1) and (2) only.",
      "Beetroot / temperature"),
    q(25,
      "Active transport of mineral ions into a root hair cell",
      {"A": "is osmosis of ions through the cell wall.",
       "B": "moves ions down a concentration gradient and does not require energy.",
       "C": "moves ions against a concentration gradient and requires energy from respiration.",
       "D": "stops when the external solution is more concentrated than the cytoplasm."},
      "C", "B",
      "Movement down a gradient with no energy is diffusion, not active transport.",
      "Ions are pumped against the gradient using energy from respiration.",
      "Active transport"),
    q(26,
      "Root hair cells take up nitrate ions from a dilute soil solution. Cyanide, which stops respiration, is added. Nitrate uptake falls sharply. This shows that the uptake",
      {"A": "requires energy from respiration, so it is active transport.",
       "B": "is simple diffusion, which always needs cyanide.",
       "C": "is osmosis of nitrate through the cell wall.",
       "D": "does not use the cell membrane."},
      "A", "C",
      "Osmosis is water through a membrane, not nitrate, and it does not need respiration.",
      "Stopping respiration stops the pump, so the process is active transport.",
      "Active transport"),
    q(27,
      "Which comparison of facilitated diffusion and active transport is correct?",
      {"A": "Facilitated diffusion: down the gradient, using a protein carrier, no ATP. Active transport: against the gradient, using a protein carrier, ATP required.",
       "B": "Facilitated diffusion: against the gradient, ATP required. Active transport: down the gradient, no ATP.",
       "C": "Both move substances against the gradient. Only active transport uses a carrier.",
       "D": "Neither uses membrane proteins."},
      "A", "B",
      "The two directions and the ATP requirement are often swapped.",
      "Facilitated diffusion is passive and down the gradient. Active transport uses ATP and can go against the gradient.",
      "Active transport"),
    q(28,
      "Which processes need energy from respiration?\n(1) Diffusion of oxygen into a cell\n(2) Osmosis of water into a root hair\n(3) Uptake of mineral ions from a dilute soil solution",
      {"A": "(3) only", "B": "(1) and (3) only", "C": "(2) and (3) only", "D": "(1), (2) and (3)"},
      "A", "B",
      "Oxygen and water move passively. Mineral ions from dilute soil are pumped in.",
      "(3) only.",
      "Active transport"),
    q(29,
      "Glucose is absorbed from the small intestine into the blood. At first the glucose concentration is higher in the intestine. Later it is higher in the epithelial cells, but absorption continues. Which processes are used, in order?",
      {"A": "Diffusion, then active transport",
       "B": "Active transport only, from the start",
       "C": "Osmosis only",
       "D": "Diffusion only, throughout"},
      "A", "D",
      "Once the gradient reverses, diffusion cannot continue to load the cells. A pump is needed.",
      "Down the gradient first (diffusion), then against it (active transport).",
      "Active transport"),
    q(30,
      "Which statement about a fully plasmolysed plant cell is correct?",
      {"A": "The cell membrane has pulled away from the cell wall. The space between them is filled with the external solution.",
       "B": "The cell wall has pulled away from the membrane.",
       "C": "The vacuole has burst through the wall.",
       "D": "The cell has no membrane left."},
      "A", "B",
      "The wall is rigid. It is the living contents (membrane and cytoplasm) that shrink away.",
      "The membrane pulls away from the wall. External solution fills the gap.",
      "Plant cells"),
    q(31,
      "A plasmolysed onion cell is then mounted in distilled water. If the cell is still living, what is observed?",
      {"A": "The cell bursts at once.",
       "B": "The cytoplasm expands and presses against the wall again (deplasmolysis).",
       "C": "The wall dissolves.",
       "D": "No change, because plasmolysis is irreversible in a living cell."},
      "B", "D",
      "In a living cell the membrane still controls water movement, so water can re-enter and turgor returns.",
      "Water enters and the cell recovers turgor.",
      "Plant cells"),
    q(32,
      "Which list of processes that can occur across a living cell membrane is correct?",
      {"A": "Osmosis only",
       "B": "Active transport only",
       "C": "Diffusion of starch, protein and DNA",
       "D": "Diffusion, osmosis, facilitated diffusion and active transport"},
      "D", "A",
      "A living membrane supports more than osmosis. Large polymers do not cross by simple diffusion.",
      "Diffusion, osmosis, facilitated diffusion and active transport can all occur.",
      "Membrane vs wall"),
]

bank = [
    {"id": "1", "title": "Practice 1", "subtitle": "Diffusion, osmosis and cells", "items": p1},
    {"id": "2", "title": "Practice 2", "subtitle": "Experiments and active transport", "items": p2},
]

out = Path(__file__).with_name("questions.js")
out.write_text("window.MEMBRANE_BANK = " + json.dumps(bank, ensure_ascii=False) + ";\n", encoding="utf-8")
print("wrote", out, "items", len(p1), len(p2))
